### ISSUE TITLE
get_mta_gtf_data.py url error

### ISSUE THREAD

**Issue by frankpd** [anastasiaclark/MTA-Mass-Transit#1]
Hey Anastasia!

I'm running the get_mta_gtfs_data.py script and am getting a url error. I've traced it to line 65:

`urllib.request.urlretrieve(os.path.join(base_path, k), os.path.join(server_path, mon_year, folders_match[v], name))`

I think it's failing because I'm on a Windows machine which uses backslashes for directories. So if you use os.path.join to create the url path, it creates this:

'http://web.mta.info/developers\\data/nyct/subway/google_transit.zip'

Since a url will always use a forward slash, I replaced the first part with this:

`"".join([base_path,"/",k])`

That worked and formed the url correctly, but then the script takes a really long time to run. I'm running it now and it's taken 15 minutes just to do the first few files. Any ideas? I'm writing to the server, so I will experiment with writing to the hard drive.

Best - Frank

**Comment by anastasiaclark** [comment]
not, sure why it takes long. I updated the line to account for any OS machine and checked it on my both Mac and Windows machines; all run fine.
