### ISSUE TITLE
create_BUS_lines.py change in express bus designations

### ISSUE THREAD

**Issue by frankpd** [anastasiaclark/MTA-Mass-Transit#2]
Hey Anastasia,

The MTA has recently changed the designation of the Express Bus services that run from Staten Island to Manhattan. Originally these were labeled as X1, X2, etc but now the new designation is SIM1, SIM2, etc. Because of this change, these bus routes are not being pulled into the express route file but are ending up in the local route file instead. There may also be some impact on the express and local stops files as well. I think line 44 is what needs to change: 

`local = shapes['route_id'].str.match(r'\w\d+|BX\d+') # creates a boolean mask with True values for local services`

Regular expressions are mostly beyond my comprehension. I checked and saw that this was the possible list of current designations for express buses:

- BxM# for Bronx
- BM# for Brooklyn
- QM# for Queens
- SIM# for Staten Island
- SIM#c variant for Staten Island where c is a single character
- X# still used for some Brooklyn and Queens services

In contrast, local buses are: Bx#, B#, M#, Q#, S#, but in a couple cases a single character may follow a number, like M#A. 

Any suggestions for modifying this would be welcome! Thanks,

Frank

**Comment by frankpd** [comment]
Ahh - also will be an issue in the stops file too. Lines 39 and 40 in create_BUS_stops.py:
```
local = unique_routes_at_stops['route_id'].str.match(
r'\w\d+|BX\d+') # creates a booleaen mask for local routes in Bus Co
```

**Comment by anastasiaclark** [comment]
fixed the bug in both scripts
