### ISSUE TITLE
Metro North Route Layers not Generated Properly

### ISSUE THREAD

**Issue by frankpd** [anastasiaclark/MTA-Mass-Transit#4]
When we created the May 2019 iteration of the layers, the underlying GTFS data for the metro-north has changed from earlier iterations. The good news is that they have finally created accurate routes that actually follow the path of rails, as opposed to straight lines that are simply drawn between stations. The bad news is that they've kept both the good and bad versions of each in the feed, so when routes are dissolved the good and bad paths are dissolved together and the result is a mess.

For this iteration we built the routes manually in QGIS by using the Points to Paths tool, and then selecting out individual lines that accurately represented each route shape_id IN (1,3,8,10,11,5).

I don't think it's worth correcting this in the script just yet. It may be better to wait and see if the data feed is adjusted to remove these bad lines. I'm just recording this issue so you're aware of it, and for us to remember what we did for next time.

**Comment by anastasiaclark** [comment]
Yeah, the feeds seem to be unpredictable from month to month. I have downloaded the GTFS feeds version in June and again in July. While the shapes.txt file stayed same in both months, the trips.txt in July listed trips for some old shape_ids that have already been removed in their June version. 

I've isolated and removed the specific individual shape_ids along the metro-north routes that were forming the generalized lines. We should be ok for now...until they decide to make other new changes we haven't though of yet :joy:
